#!/bin/bash

app_name=tabl

if [ -z "$NATIVE_IMAGE" ]; then
    echo 'Please set $NATIVE_IMAGE'
    exit 1
fi

$NATIVE_IMAGE \
    -jar target/$app_name-* \
    -H:Name=$app_name \
    -H:+ReportExceptionStackTraces \
    -H:IncludeResources=VERSION \
    --report-unsupported-elements-at-runtime \
    --verbose \
    --no-fallback \
    --no-server \
    "-J-Xmx3g"
