#!/bin/bash

app_name=tabl

rm -rf classes
mkdir classes
clojure -e "(compile 'app.main)"

if [ -z "$NATIVE_IMAGE" ]; then
    echo 'Please set $NATIVE_IMAGE'
    exit 1
fi

$NATIVE_IMAGE \
    -cp $(clojure -Spath):classes \
    -H:Name=$app_name \
    -H:+ReportExceptionStackTraces \
    -H:IncludeResources=VERSION \
    --initialize-at-build-time \
    --report-unsupported-elements-at-runtime \
    --verbose \
    --no-fallback \
    --no-server \
    "-J-Xmx3g" \
    app.main
